version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: boto3 
    update-types: ["version-update:semver-patch"] 
  - dependency-name: django
    versions:
    - ">=2.0"
