repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: check-json
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.2.1'
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix, --extend-exclude, TCH]
    - id: ruff-format
