version = 0.1
[jcm1]
[jcm1.deploy]
[jcm1.deploy.parameters]
stack_name = "aggregator-api-jcm1"
s3_bucket = "aggregator-api-sam-21edfreg43gas"
s3_prefix = "jcm1"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
tags = "dc-product=\"aggregator-api\" dc-environment=\"development\" dc-instance=\"jcm1\""

[jcm2]
[jcm2.deploy]
[jcm2.deploy.parameters]
stack_name = "aggregator-api-jcm2"
s3_bucket = "aggregator-api-sam-21edfreg43gas"
s3_prefix = "jcm2"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
tags = "dc-product=\"aggregator-api\" dc-environment=\"development\" dc-instance=\"jcm2\""
progressbar = false
fail_on_empty_changeset = false
force_upload = true

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "aggregator-api-staging"
s3_bucket = "aggregator-api-staging-deployment-via-sam-cli-fdsdg4fsga2jl"
s3_prefix = "staging"
region = "eu-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
tags = "dc-product=\"aggregator-api\" dc-environment=\"staging\""
progressbar = false
fail_on_empty_changeset = false
force_upload = true
#kms-key-id = "" # having this unset uses an AWS-managed key; it doesn't not-encrypt files


[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "aggregator-api-production"
s3_bucket = "aggregator-api-production-deployment-via-sam-cli-lksjdfoiuwerm"
s3_prefix = "production"
region = "eu-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
tags = "dc-product=\"aggregator-api\" dc-environment=\"production\""
progressbar = false
fail_on_empty_changeset = false
force_upload = true
#kms-key-id = "" # having this unset uses an AWS-managed key; it doesn't not-encrypt files
