AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aggregator-api

  The DC Aggregator API running in AWS Lambda deployed via SAM

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Parameters:
  SecretKey:
    Type: String
    Default: "okgf3ok2rfokv4p3kfodskgo23fgre;fergfds@sfwsf;2d234$32e412e1e32fg32rfgvfxkbrkof3q"
  DjangoSettingsModule:
    Type: String
    # Whilst the app is stateless, this default is safe. No production resources can be
    # reached by non-production environments, so forgetting to set this environment variable
    # in development or staging environments won't affect production. Forgetting to set it
    # in production, however, will fail safe and work as intended.
    Default: "aggregator.settings.lambda_production"
  AppDebugMode:
    Type: String
    # Only certain environments examine this variable to dis-/en-able Debug mode.
    # Specifically, the production environment has this hardcoded as False.
    Default: "False"

Resources:
  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./lambda-layers/DependenciesLayer/
      CompatibleRuntimes:
        - python3.6
    Metadata:
      BuildMethod: makefile
    RetentionPolicy: Delete
  AggregatorApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: aggregator.lambda_awsgi.lambda_handler
      Layers:
        - !Ref DependenciesLayer
      Runtime: python3.6
      MemorySize: 192
      Environment:
        Variables:
          SECRET_KEY: !Ref SecretKey
          DJANGO_SETTINGS_MODULE: !Ref DjangoSettingsModule
          DEBUG: !Ref AppDebugMode
      Events:
        HTTPRequests:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: get
        HTTPRequestRoots:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: get
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AggregatorApiHTTP:
    Description: "API Gateway endpoint URL for Prod stage for Aggregator API function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  AggregatorApiFunction:
    Description: "Aggregator API Lambda Function ARN"
    Value: !GetAtt AggregatorApiFunction.Arn
  AggregatorApiFunctionIamRole:
    Description: "Implicit IAM Role created for Aggregator API function"
    Value: !GetAtt AggregatorApiFunctionRole.Arn
  DjangoSettingsModule:
    Description: "Runtime settings module used by Django (CHECK THIS IS WHAT YOU EXPECT!)"
    Value: !Ref DjangoSettingsModule
