AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aggregator-api

  The DC Aggregator API running in AWS Lambda deployed via SAM

Globals:
  Function:
    Timeout: 10
  Api:
    BinaryMediaTypes:
      - "*/*"

Parameters:

  AppSecretKey:
    Description: "The SECRET_KEY environment variable passed to the app."
    Type: String

  AppDjangoSettingsModule:
    Description: "The DJANGO_SETTINGS_MODULE environment variable passed to the app."
    Type: String

Resources:

  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./lambda-layers/DependenciesLayer/
      CompatibleRuntimes:
        - python3.6
    Metadata:
      BuildMethod: makefile
    RetentionPolicy: Delete

  AggregatorApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: aggregator.lambda_awsgi.lambda_handler
      Layers:
        - !Ref DependenciesLayer
      Runtime: python3.6
      MemorySize: 192
      Environment:
        Variables:
          SECRET_KEY: !Ref AppSecretKey
          DJANGO_SETTINGS_MODULE: !Ref AppDjangoSettingsModule
      Events:
        HTTPRequests:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: GET
        HTTPRequestRoots:
          Type: Api
          Properties:
            Path: /
            Method: GET
      AutoPublishAlias: Live
      DeploymentPreference:
        Type: AllAtOnce

Outputs:
  AggregatorApiFqdn:
    Description: "API Gateway endpoint FQDN for Aggregator API function"
    Value: !Sub "${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com"
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", "AggregatorApiFqdn" ] ]
