AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aggregator-api

  The DC Aggregator API running in AWS Lambda deployed via SAM

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./lambda-layers/DependenciesLayer/
      CompatibleRuntimes:
        - python3.6
    Metadata:
      BuildMethod: makefile
  AggregatorApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: aggregator.lambda_awsgi.lambda_handler
      Layers:
        - !Ref DependenciesLayer
      Runtime: python3.6
      Environment:
        Variables:
          SECRET_KEY: "gfrejiok34mfk54mvk54lv9fdv3i4gf,lwqd;3rjv823f903rf;;vsf'nytppoqkdfmskfmerk#"
      Events:
        HTTPRequests:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: get
        HTTPRequestRoots:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: get
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AggregatorApiHTTP:
    Description: "API Gateway endpoint URL for Prod stage for Aggregator API function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  AggregatorApiFunction:
    Description: "Aggregator API Lambda Function ARN"
    Value: !GetAtt AggregatorApiFunction.Arn
  AggregatorApiFunctionIamRole:
    Description: "Implicit IAM Role created for Aggregator API function"
    Value: !GetAtt AggregatorApiFunctionRole.Arn
