# This file and its quirks are documented here:
# https://github.com/aws/aws-sam-cli/blob/develop/docs/sam-config-docs.md
version = 0.1

####################################################################################
## NB: Don't insert a "default" profile in this file! ##############################
###### Only use named, per-environment profiles. ###################################
###### This will help guard against accidentally targetting the wrong environment. #
####################################################################################

[development]

[development.deploy]
[development.deploy.parameters]
stack_name = "AggregatorApiApp-development"
s3_bucket = "aggregator-api-deployment-artifacts-development-075b482c18"
s3_prefix = "development"
region = "eu-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
tags = "dc-product=\"aggregator-api\" dc-environment=\"development\""
progressbar = false
fail_on_empty_changeset = false
force_upload = true
# Using a "parameter_overrides" setting here would block using CI envvars, as only
# one overrides source is used and this source doesn't pass through shell interpolation.

[development-public-access]
[development-public-access.deploy]
[development-public-access.deploy.parameters]
template = "public-access-template.yaml"
stack_name = "AggregatorApiPublicAccess-development"
region = "eu-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
tags = "dc-product=\"aggregator-api\" dc-environment=\"development\""
progressbar = false
fail_on_empty_changeset = false
force_upload = true
# Using a "parameter_overrides" setting here would block using CI envvars, as only
# one overrides source is used and this source doesn't pass through shell interpolation.

[development.logs]
[development.logs.parameters]
stack_name = "AggregatorApiApp-development"
name = "AggregatorApiFunction"
region = "eu-west-2"
