# This file and its quirks are documented here:
# https://github.com/aws/aws-sam-cli/blob/develop/docs/sam-config-docs.md
version = 0.1

####################################################################################
## NB: Don't insert a "default" profile in this file! ##############################
###### Only use named, per-environment profiles. ###################################
###### This will help guard against accidentally targetting the wrong environment. #
####################################################################################

[staging]

[staging.deploy]
[staging.deploy.parameters]
stack_name = "AggregatorApiApp-staging"
s3_bucket = "aggregator-api-deployment-artifacts-staging-3jfac0gjro"
s3_prefix = "staging"
region = "eu-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
tags = "dc-product=\"aggregator-api\" dc-environment=\"staging\""
progressbar = false
fail_on_empty_changeset = false
force_upload = true
# Using a "parameter_overrides" setting here would block using CI envvars, as only
# one overrides source is used and this source doesn't pass through shell interpolation.

[staging-public-access]
[staging-public-access.deploy]
[staging-public-access.deploy.parameters]
template = "public-access-template.yaml"
stack_name = "AggregatorApiPublicAccess-staging"
region = "eu-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
tags = "dc-product=\"aggregator-api\" dc-environment=\"staging\""
progressbar = false
fail_on_empty_changeset = false
force_upload = true
# Using a "parameter_overrides" setting here would block using CI envvars, as only
# one overrides source is used and this source doesn't pass through shell interpolation.

[staging.logs]
[staging.logs.parameters]
stack_name = "AggregatorApiApp-staging"
name = "AggregatorApiFunction"
region = "eu-west-2"




[jcm1]

[jcm1.deploy]
[jcm1.deploy.parameters]
stack_name = "AggregatorApiApp-jcm1"
s3_bucket = "aggregator-api-deployment-artifacts-development-075b482c18"
s3_prefix = "jcm1"
region = "eu-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
tags = 'dc-product="aggregator-api" dc-environment="development" dc-instance="jcm1"'
# These parameter overrides are *not* merged with those provided directly to the
# `sam XXXX` CLI command: those provided at the CLI are the *only* ones used.
parameter_overrides = """
  AppDjangoSettingsModule=aggregator.settings.lambda_no_debug_merged_assets \
  AppSecretKey=badf00d \
"""
#  PublicFqdn=environments.womblelabs.co.uk \

[jcm1-public-access]
[jcm1-public-access.deploy]
[jcm1-public-access.deploy.parameters]
template = "public-access-template.yaml"
stack_name = "AggregatorApiPublicAccess-jcm1"
region = "eu-west-2"
capabilities "CAPABILITY_IAM"
parameter_overrides = """
  LambdaStackName="AggregatorApiApp-jcm1" \
  CertificateArn="arn:aws:acm:us-east-1:489559689862:certificate/7177497b-8705-461b-832a-b3b98699e24e" \
  PublicFqdn=environments.womblelabs.co.uk \
"""

[jcm1.logs]
[jcm1.logs.parameters]
stack_name = "AggregatorApiApp-jcm1"
name = "AggregatorApiFunction"
region = "eu-west-2"
