# Generated by Django 4.1.2 on 2023-12-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apikey",
            name="api_plan",
        ),
        migrations.AddField(
            model_name="apikey",
            name="key_type",
            field=models.CharField(
                choices=[
                    ("development", "Development"),
                    ("production", "Production"),
                ],
                default="development",
                help_text="The plan for this API key. Only one production key allowed.",
                max_length=100,
                verbose_name="API plan",
            ),
        ),
    ]
