[project]
name = "api-auth"
version = "0.0.0"
description = "API endpoint for handling token auth"
requires-python = "==3.12.*"
dependencies = [
    "dc-api-common"
]

[tool.uv.sources]
dc-api-common = { workspace = true }

[tool.uv]
package = false
